CONSEQFILES = make-tex-table.py \
	cut.json \
	obtrusive-0.json \
	obtrusive-1.json \
	obtrusive-2.json \
	overwhelmed.json \
	pickpocket.json \
	premium.json \
	surprise.json \
	template.json \
	under-observation.json \
	wrong-person-0.json \
	wrong-person-1.json \
	wrong-person-2.json

consequences.tex: $(CONSEQFILES)
	python3 make-tex-table.py
